#!/usr/bin/env bash
if [ -z "$1" ]
then
	echo "Usage: remove_control_characters filename" 1>&2
	exit
fi

for i in {0..31}
do
	# Convert decimal to hex.
	hex=$(printf "%x" $i)
	sed -i 's/\x'$(echo $hex)'//g' $1
done
